CREATE DATABASE IF NOT EXISTS job_tracker_db;
USE job_tracker_db;

CREATE TABLE applications (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    company_name VARCHAR(100) NOT NULL,
    role VARCHAR(100) NOT NULL,
    date_applied DATE NOT NULL,
    stage ENUM('APPLIED', 'SCREENING', 'INTERVIEW', 'FINAL_ROUND', 'OFFER') NOT NULL DEFAULT 'APPLIED',
    status ENUM('PENDING', 'REJECTED', 'GHOSTED', 'ACCEPTED') NOT NULL DEFAULT 'PENDING',
    job_url VARCHAR(255),
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE journal_entries (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(150),
    content TEXT NOT NULL,
    mood ENUM('MOTIVATED', 'NEUTRAL', 'ANXIOUS', 'DISCOURAGED', 'HOPEFUL') NOT NULL,
    entry_date DATE NOT NULL,
    application_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE SET NULL
);